name = "calendar-convert"
main = "_worker.js"
compatibility_date = "2025-09-02"

# Serve the Vite build output as static assets
assets = { directory = "dist", binding = "ASSETS" }

[env.preview]
name = "calendar-convert-preview"

[[routes]]
pattern = "availability.werda.pl"
custom_domain = true
